site_name: C++Spec
site_url: http://cppspec.readthedocs.org
site_description: BDD testing for C++
site_author: Katherine Whitlock

repo_url: htpps://github.com/toroidal-code/cppspec/tree/master/docs

theme: readthedocs

pages:
  - Home: index.md
  - Syntax:
    - Describe: syntax/describe.md

markdown_extensions:
  - admonition:

copyright: Copyright © 2014-2016 Katherine Whitlock